# Generated by Django 2.1.4 on 2018-12-13 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('finclass', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('expense_ratio', models.DecimalField(decimal_places=3, max_digits=4)),
                ('assets', models.ManyToManyField(through='etf.AssetInvestment', to='etf.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='EtfInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.Etf')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etfs', models.ManyToManyField(through='etf.EtfInvestment', to='etf.Etf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='etfinvestment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.Portfolio'),
        ),
        migrations.AddField(
            model_name='assetinvestment',
            name='etf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.Etf'),
        ),
    ]
