# Generated by Django 3.2 on 2021-04-25 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0003_etfprovider_rawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
