# Generated by Django 3.2 on 2021-04-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0004_rawdata_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etfinvestment',
            old_name='investment',
            new_name='portfolio',
        ),
        migrations.RemoveField(
            model_name='etf',
            name='short_title',
        ),
        migrations.AlterField(
            model_name='etf',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
