# Generated by Django 3.2 on 2021-04-25 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0005_auto_20210425_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='holdings_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etf',
            name='inception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etf',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etf.etfprovider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etf',
            name='shares_outstanding',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='etf',
            unique_together={('provider', 'title')},
        ),
    ]
