# Generated by Django 3.2 on 2021-04-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0007_auto_20210426_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetInvestment',
            new_name='AssetInEtf',
        ),
    ]
