# Generated by Django 3.2 on 2021-04-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0009_auto_20210426_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtfInPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.etf')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etf.portfolio')),
            ],
        ),
        migrations.AlterField(
            model_name='assetinetf',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='EtfInvestment',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='etfs',
            field=models.ManyToManyField(through='etf.EtfInPortfolio', to='etf.Etf'),
        ),
    ]
