# Generated by Django 3.2 on 2021-04-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0010_auto_20210426_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinetf',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
