# Generated by Django 3.2 on 2021-04-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0011_alter_assetinetf_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etf',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='etf',
            unique_together={('provider', 'name')},
        ),
    ]
