# Generated by Django 3.2 on 2021-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0014_auto_20210426_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='overrides',
            field=models.TextField(blank=True, null=True),
        ),
    ]
